name: Ergothérapeute et équithérapeute Dinan Saint-Malo
description: Ergothérapeute et équithérapeute Dinan Saint-Malo Rennes - Ille et Vilaine - Bretagne
baseurl: ""
url: https://equitherapeute-ergotherapeute.tiphainedelarue.fr

plugins:
  - jekyll-sitemap

exclude: ["Gemfile", "Gemfile.lock", "docs", "vendor"]
